### ISSUE TITLE
Problema Parcial: De Mayor a Menor

### ISSUE THREAD

**Issue by axelitz** [fiuba-labo-de-micro-miercoles/2019-2c-primer-proyecto-axelitz#1]
Dejé un archivo en la carpeta de _codigo_ correspondiente a un ejercicio de parcial que pedía lo siguiente:
_Dado un vector de 25 números en memoria RAM externa ubicado a partir de la dirección **Vec1**, reescribirlo ordenado de mayor a menor a partir de la dirección **Vec2**. Los numeros son enteros sin signo y los vectores no se solapan en ninguna posición. _
Estoy teniendo problemas para compilarlo ya que no estoy pudiendo cargar en R14 y R15 las constantes _cant_nros_(la cantidad de números a ordenar en la tabla) y la posición de memoria _Vec2_ para llenar la nueva tabla. De paso, quiero ver si el algoritmo que estoy utilizando está bien, que sería ir buscando el mayor "local", es decir desde la posición 1 cuál es el mayor correspondiente para el caso (para la primera posición, buscar el mayor de todos), y una vez encontrado ese buscar el mayor para la posición 2 (el segundo mayor), y así hasta la anteúltima posición.
Desde ya, muchas gracias y saludos,
Axel Itzcovitz

**Comment by rarias** [comment]
Fijate en el set de instrucciones los parámetros válidos de LDI

**Comment by axelitz** [comment]
Ok, ya cambié los registros R14 y R15 por los registros R22 y R23, respectivamente. No hay errores de compilación, pero al querer correr el programa me tira el siguiente mensaje:
_AVR Simulator: Invalid opcode 0xffff at address 0x00c8c8_
Buscando en Internet encontré que debería ser un problema del Stack (overflow o algo por ese lado), pero el Stack solamente se utiliza al comienzo para inicializarlo, por lo que no veo el problema ahí. ¿Hay algo que no esté viendo del Stack o el problema va por otro lado?

**Comment by rarias** [comment]
Estoy mirando tu código,
Vas con RJMP a ORDENAR y querés volver con RET (???), eso no funca, tenés que ir con RCALL para volver con RET.
Al hacer un RET sin un RCALL previo, el PC se carga con una dirección inexistente en la pila.

**Comment by rarias** [comment]
Los equs  al principio tampoco están bien.  Para poner datos en RAM definís un segmento .DSEG
y ponés las etiquetas de los nombres de los vectores (detalle, los comentarios de ambas etiquetas son idénticos, pero la función de un vector y el otro no)

**Comment by rarias** [comment]
El .org de la línea 80 rompe todo, está muy feo eso

**Comment by axelitz** [comment]
> Estoy mirando tu código,
> Vas con RJMP a ORDENAR y querés volver con RET (???), eso no funca, tenés que ir con RCALL para volver con RET.
> Al hacer un RET sin un RCALL previo, el PC se carga con una dirección inexistente en la pila.

Así es, ya corregí ese error de desprevenido.

**Comment by axelitz** [comment]
> Los equs al principio tampoco están bien. Para poner datos en RAM definís un segmento .DSEG
> y ponés las etiquetas de los nombres de los vectores (detalle, los comentarios de ambas etiquetas son idénticos, pero la función de un vector y el otro no)

La idea de los .EQU sería definir como constantes las posiciones de memoria donde se encuentra la tabla original y donde tengo que guardar, así como también la cantidad de números de la tabla. No busco guardar estos datos en RAM. Según recuerdo, para definir estas constantes no hace falta que vayan dentro de un .DSEG. Es así?

**Comment by axelitz** [comment]
> El .org de la línea 80 rompe todo, está muy feo eso

Acá la idea es definir en la posición de memoria _Vec1_ la tabla a ordenar. Siendo Vec1 la constante correspondiente, y definida con el EQU, no está bien utilizada la directiva .ORG?

**Comment by rarias** [comment]
EQU no se usa para definir una dirección de memoria

**Comment by rarias** [comment]
Simplemente se pone la etiqueta, 2 puntos, y .BYTE si estás en RAM (DSEG) o .DB si estás en flash

**Comment by rarias** [comment]
No se usa .ORG para poner una TABLA en una posición específica (a menos que exista una muy buena razón para hacerlo).   Simplemente se pone la tabla y donde cae queda.

**Comment by axelitz** [comment]
> EQU no se usa para definir una dirección de memoria

Habría alguna manera de definir una dirección de memoria? O no se pasa por una variable para asignarle datos al mismo?

**Comment by axelitz** [comment]
> No se usa .ORG para poner una TABLA en una posición específica (a menos que exista una muy buena razón para hacerlo). Simplemente se pone la tabla y donde cae queda.

Entendido, me manejo con la etiqueta tabla y listo.

**Comment by axelitz** [comment]
Actualicé el código corrigiendo lo hablado (si bien el ejercicio plantea que la tabla está en RAM, la defino en FLASH para poder manipular más fácilmente los elementos de la misma). Sin embargo, estoy teniendo problemas para guardar datos en las direcciones de memoria del puntero Z (es decir, no me está funcionando la instrucción ST para este puntero, porque según verifiqué para el puntero X funciona bien).  Qué es lo que se me está pasando?
